language: csharp
os:
  - linux

# .NET CLI require Ubuntu 14.04
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8

mono: none
dotnet: 2.1.403

before_script:
  - '[[ $TRAVIS_TAG =~ (^v[0-9]+.[0-9]+.[0-9]+) ]] && CONFIGURATION="Release" || CONFIGURATION="Debug"'
  - dotnet tool install -g Cake.Tool --version 0.30.0
  - export PATH="$PATH:~/.dotnet/tools"

script:
  - dotnet cake --target=Default --configuration=$CONFIGURATION --verbosity=diagnostic

after_success:
  - dotnet cake --target=PublishPackages --configuration=$CONFIGURATION --verbosity=diagnostic

cache:
  directories:
    - .packages
    - .tools
